In [1]:
# ! pip install requests pandas matplotlib numpy

Editar para reusar:

In [2]:
from pathlib import Path

PROJECT_PATH = Path("/Users/daragama/Documents/Master25/Tesis/datos_semisinteticos/")
DATAPATH = PROJECT_PATH  / "data"
OUTPUTPATH = PROJECT_PATH / "output"
print(f"DATAPATH: {DATAPATH}")

DATAPATH: /Users/daragama/Documents/Master25/Tesis/datos_semisinteticos/data

# Revisemos 2024

Fuente: https://www.inegi.org.mx/programas/edr/

In [3]:
import pandas as pd
import numpy as np


year = 2024
YEAR_DATAPATH = DATAPATH / "raw" / f"{year}"
raw_deaths_data_path = YEAR_DATAPATH /  "conjunto_de_datos"

year_data_file = list(raw_deaths_data_path.glob("*.csv"))

# open csv in a pandas dataframe
year_data = pd.read_csv(year_data_file[0], low_memory=False) # low_memory=False added to avoid DtypeWarning: Columns (0: maternas) have mixed types.

year_data

,ent_regis,mun_regis,tloc_regis,loc_regis,ent_resid,mun_resid,tloc_resid,loc_resid,ent_ocurr,mun_ocurr,...,complicaro,dia_cert,mes_cert,anio_cert,maternas,ent_ocules,mun_ocules,loc_ocules,razon_m,dis_re_oax
0,1,2,5,1,1,1,15,1,1,5,...,8,23,1,2024,NaN,88,888,8888,0,999
1,1,2,5,59,1,2,1,15,1,1,...,8,17,1,2024,NaN,88,888,8888,0,999
2,1,3,8,1,1,3,5,55,1,1,...,8,12,1,2024,NaN,88,888,8888,0,999
3,1,3,8,1,1,3,2,33,1,3,...,8,17,1,2024,NaN,88,888,8888,0,999
4,1,2,5,1,1,1,15,1,1,1,...,9,14,12,2023,NaN,88,888,8888,0,999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
819667,32,10,13,1,99,999,99,9999,32,10,...,8,16,2,2024,NaN,99,999,9999,0,999
819668,32,56,13,1,32,56,13,1,32,56,...,9,4,1,2024,NaN,88,888,8888,0,999
819669,32,56,13,1,14,61,4,1,32,56,...,9,28,11,2024,NaN,88,888,8888,0,999
819670,32,56,13,1,32,55,6,1,32,56,...,9,6,1,2024,NaN,88,888,8888,0,999
819671,32,17,13,1,32,17,13,1,32,17,...,9,30,12,2024,NaN,32,17,1,0,999

In [4]:
year_data.columns

Index(['ent_regis', 'mun_regis', 'tloc_regis', 'loc_regis', 'ent_resid',
       'mun_resid', 'tloc_resid', 'loc_resid', 'ent_ocurr', 'mun_ocurr',
       'tloc_ocurr', 'loc_ocurr', 'causa_def', 'cod_adicio', 'lista_mex',
       'sexo', 'ent_nac', 'afromex', 'conindig', 'lengua', 'cve_lengua',
       'nacionalid', 'nacesp_cve', 'edad', 'sem_gest', 'gramos', 'dia_ocurr',
       'mes_ocurr', 'anio_ocur', 'dia_regis', 'mes_regis', 'anio_regis',
       'dia_nacim', 'mes_nacim', 'anio_nacim', 'cond_act', 'ocupacion',
       'escolarida', 'edo_civil', 'tipo_defun', 'ocurr_trab', 'lugar_ocur',
       'par_agre', 'vio_fami', 'asist_medi', 'cirugia', 'natviole',
       'necropsia', 'usonecrops', 'encefalica', 'donador', 'sitio_ocur',
       'cond_cert', 'derechohab', 'embarazo', 'rel_emba', 'horas', 'minutos',
       'capitulo', 'grupo', 'lista1', 'gr_lismex', 'area_ur', 'edad_agru',
       'complicaro', 'dia_cert', 'mes_cert', 'anio_cert', 'maternas',
       'ent_ocules', 'mun_ocules', 'loc_ocules', 'razon_m', 'dis_re_oax'],
      dtype='str')

Los datos están "códificados, cada columna tiene un catálogo para saber a que corresponde cada valor.

# "Decodificar"

In [5]:
# el archivo está mal códigificado, por lo que se debe reparar el mojibake
def reparar_mojibake(texto):
    if isinstance(texto, str):
        try:
            return texto.encode("latin1").decode("utf-8")
        except (UnicodeEncodeError, UnicodeDecodeError):
            return texto
    return texto

In [6]:
data_dic = YEAR_DATAPATH / "diccionario_de_datos"
dic_file = list(data_dic.glob("*.csv"))[0]
data_dictionary = pd.read_csv(dic_file, low_memory=False, encoding='utf-8') # low_memory=False added to avoid DtypeWarning: Columns (0: maternas) have mixed types.
# apply reparar_mojibake to the columns names
data_dictionary.rename(columns={'NEMÃ“NICO': 'NEMONICO', 'CATÃLOGO' : 'CATALOGO'}, inplace=True) # no es buena práctica usar acentos en nombres de columnas
data_dictionary

,NOMBRE_CAMPO,LONGITUD,TIPO,NEMONICO,CATALOGO,RANGO_CLAVES
0,Entidad de registro,2,C,ent_regis,entidad_municipio_localidad_2024,01 … 32\t
1,Municipio o demarcaciÃ³n territorial de registro,3,C,mun_regis,entidad_municipio_localidad_2024,001 … 570 ...
2,TamaÃ±o de localidad de registro,2,N,tloc_regis,tamaÃ±o_localidad,"1 … 17, 99 ..."
3,Localidad de registro,4,C,loc_regis,entidad_municipio_localidad_2024,"0001 … 6999, 7777 ..."
4,Entidad de residencia habitual del (la) fallec...,2,C,ent_resid,entidad_municipio_localidad_2024,"01 … 35, 99 ..."
...,...,...,...,...,...,...
69,Entidad de ocurrencia de la lesiÃ³n,2,C,ent_ocules,entidad_municipio_localidad_2024,"01 … 35, 88, 99 ..."
70,Municipio o demarcaciÃ³n territorial de ocurre...,3,C,mun_ocules,entidad_municipio_localidad_2024,"001 … 570, 888, 999 ..."
71,Localidad de ocurrencia de la lesiÃ³n,4,C,loc_ocules,entidad_municipio_localidad_2024,"0001 … 6999, 7777, 8888, 9999 ..."
72,Defunciones para calcular la razÃ³n de la mort...,1,N,razon_m,razon_materna,"1, Nulo"
73,Distritos de registro de Oaxaca,3,C,dis_re_oax,entidad_municipio_localidad_2024,"901 … 930, 999"

In [7]:
# reparar data_dictionary
data_dictionary = data_dictionary.map(reparar_mojibake)
data_dictionary.head()

,NOMBRE_CAMPO,LONGITUD,TIPO,NEMONICO,CATALOGO,RANGO_CLAVES
0,Entidad de registro,2,C,ent_regis,entidad_municipio_localidad_2024,01 … 32\t
1,Municipio o demarcación territorial de registro,3,C,mun_regis,entidad_municipio_localidad_2024,001 … 570 ...
2,Tamaño de localidad de registro,2,N,tloc_regis,tamaño_localidad,"1 … 17, 99 ..."
3,Localidad de registro,4,C,loc_regis,entidad_municipio_localidad_2024,"0001 … 6999, 7777 ..."
4,Entidad de residencia habitual del (la) fallec...,2,C,ent_resid,entidad_municipio_localidad_2024,"01 … 35, 99 ..."

## ENTIDAD

In [8]:
item_dic = data_dictionary.iloc[0]
nemonico = item_dic['NEMONICO']
catalogo = item_dic['CATALOGO'] + ".csv"
catalogo_path = YEAR_DATAPATH / "catalogos" / catalogo
df_catalogo = pd.read_csv(catalogo_path, low_memory=False)

In [9]:
# Seleccionar solo las entidades y columnas de interes
mapeo_ent = df_catalogo.loc[df_catalogo['cve_mun']==0, ['cve_ent','nom_loc']]
# cambiar nombre columnas
mapeo_ent.rename(columns={"cve_ent":"ent_code", "nom_loc": "ent_nom"}, inplace=True)
# mapeo_ent.columns = ['ent_code', 'ent_nom']
display(mapeo_ent)
mapeo_ent.to_csv( OUTPUTPATH / "mapeo_entidades.csv", index=False)

       ent_code                                       ent_nom
0             1                                Aguascalientes
157           2                               Baja California
296           3                           Baja California Sur
362           4                                      Campeche
608           5                          Coahuila de Zaragoza
840           6                                        Colima
951           7                                       Chiapas
3248          8                                     Chihuahua
3823          9                              Ciudad de México
3883         10                                       Durango
4383         11                                    Guanajuato
5984         12                                      Guerrero
7015         13                                       Hidalgo
8420         14                                       Jalisco
9523         15                                        México
11427        16                           Michoacán de Ocampo
12904        17                                       Morelos
13166        18                                       Nayarit
13529        19                                    Nuevo León
13790        20                                        Oaxaca
16782        21                                        Puebla
18896        22                                     Querétaro
19438        23                                  Quintana Roo
19615        24                               San Luis Potosí
20706        25                                       Sinaloa
21397        26                                        Sonora
21946        27                                       Tabasco
22963        28                                    Tamaulipas
23332        29                                      Tlaxcala
23721        30               Veracruz de Ignacio de la Llave
27227        31                                       Yucatán
27775        32                                     Zacatecas
28488        33                Estados Unidos de Norteamérica
28491        88  Entidad no aplica para A00 - R99 Y V90 - Y89
28494        99                       Entidad no especificada

In [10]:
columnas_de_ent = ["ent_regis", "ent_resid", "ent_ocurr", "ent_nac", "ent_ocules"]
year_data_fixed = year_data.copy()
mapeo_ent = dict(zip(mapeo_ent["ent_code"], mapeo_ent["ent_nom"]))

for col in columnas_de_ent:
    col_name = col + "_nom"
    year_data_fixed[col_name] = year_data_fixed[col].map(mapeo_ent)

In [11]:
# check nans
year_data_fixed[["ent_regis", "ent_regis_nom"]].isna().sum()

ent_regis        0
ent_regis_nom    0
dtype: int64

### Check Localidad

In [12]:
# check some data
columns_to_drop = columnas_de_ent
year_data_fixed[year_data_fixed['ent_resid'] == 32][['ent_resid_nom']].value_counts()

ent_resid_nom
Zacatecas        10304
Name: count, dtype: int64

## MUNICIPIO

In [13]:
# Seleccionar solo las entidades y columnas de interes
mapeo_mun = df_catalogo.loc[df_catalogo['cve_loc']==0, ['cve_ent', 'cve_mun','nom_loc']]
# cambiar nombre columnas
mapeo_mun.rename(columns={"cve_ent":"ent_code", "cve_mun": "mun_code", "nom_loc": "mun_nom"}, inplace=True)
mapeo_mun

       ent_code  mun_code                                         mun_nom
0             1         0                                  Aguascalientes
1             1         1                                  Aguascalientes
28            1         2                                        Asientos
54            1         3                                        Calvillo
72            1         4                                           Cosío
...         ...       ...                                             ...
28489        33       999                       Municipio no especificado
28491        88         0    Entidad no aplica para A00 - R99 Y V90 - Y89
28492        88       888  Municipio no aplica para A00 - R99 Y V90 - Y89
28494        99         0                         Entidad no especificada
28495        99       999                       Municipio no especificado

[2573 rows x 3 columns]

In [14]:
# mapeo_mun = dict(zip(mapeo_mun["mun_code"], mapeo_mun["mun_nom"]))

# columnas_de_mun = ["mun_regis", "mun_resid", "mun_ocurr", "mun_ocules"]
columnas_de_mun = ["regis", "resid", "ocurr", "ocules"]

for col in columnas_de_mun:
    col_num = "mun_" + col
    col_ent = "ent_" + col
    col_name = "mun_" + col + "_nom"
    mapeo_tmp = mapeo_mun.rename(columns={"ent_code": col_ent, "mun_code": col_num, "mun_nom": col_name})
    # Unir ambas tablas
    year_data_fixed = pd.merge(year_data_fixed, mapeo_tmp, on=[col_ent, col_num], how='left' )

In [15]:
# check nans
year_data_fixed[["mun_regis", "mun_regis_nom"]].isna().sum()

mun_regis        0
mun_regis_nom    0
dtype: int64

### Check Municipios

In [16]:
columnas_mun_drop = ["mun_regis", "mun_resid", "mun_ocurr", "mun_ocules"]
columns_to_drop += columnas_mun_drop
test = year_data_fixed[year_data_fixed['mun_regis_nom'] == 'San Felipe']
test = test[['ent_regis_nom', 'mun_regis_nom']].groupby(['ent_regis_nom', 'mun_regis_nom'])
test[['ent_regis_nom']].value_counts()

ent_regis_nom    mun_regis_nom
Baja California  San Felipe       123
Guanajuato       San Felipe       478
Yucatán          San Felipe        18
Name: count, dtype: int64

In [17]:
columns_to_drop

['ent_regis',
 'ent_resid',
 'ent_ocurr',
 'ent_nac',
 'ent_ocules',
 'mun_regis',
 'mun_resid',
 'mun_ocurr',
 'mun_ocules']

## LOCALIDAD

In [18]:
def agregar_localidad(df, mapeo_lugar, tipo):
    """
    Agrega el nombre de la localidad usando las claves
    entidad + municipio + localidad del catálogo INEGI.
    """

    ent = f"ent_{tipo}"
    mun = f"mun_{tipo}"
    loc = f"loc_{tipo}"
    loc_nom = f"{loc}_nom"

    mapeo_loc = mapeo_lugar[
        ["cve_ent", "cve_mun", "cve_loc", "nom_loc"]
    ].copy()

    # Asegurar el mismo tipo de dato en las claves
    df[ent] = df[ent].astype(str)
    df[mun] = df[mun].astype(str)
    df[loc] = df[loc].astype(str)

    mapeo_loc["cve_ent"] = mapeo_loc["cve_ent"].astype(str)
    mapeo_loc["cve_mun"] = mapeo_loc["cve_mun"].astype(str)
    mapeo_loc["cve_loc"] = mapeo_loc["cve_loc"].astype(str)

    mapeo_loc.columns = [ent, mun, loc, loc_nom]

    df = pd.merge(
        df,
        mapeo_loc,
        on=[ent, mun, loc],
        how="left"
    )

    return df

In [19]:
year_data_fixed = agregar_localidad(
    year_data_fixed, df_catalogo, "regis"
)

year_data_fixed = agregar_localidad(
    year_data_fixed, df_catalogo, "resid"
)

year_data_fixed = agregar_localidad(
    year_data_fixed, df_catalogo, "ocurr"
)

year_data_fixed = agregar_localidad(
    year_data_fixed, df_catalogo, "ocules"
)

### Check Localidad

In [20]:

benito_juarez = year_data_fixed[year_data_fixed['loc_regis_nom'] == 'Benito Juárez']
benito_juarez[['ent_regis_nom', 'mun_regis_nom', 'loc_regis_nom']].value_counts()

ent_regis_nom                    mun_regis_nom        loc_regis_nom
Ciudad de México                 Benito Juárez        Benito Juárez    205
Veracruz de Ignacio de la Llave  Benito Juárez        Benito Juárez    113
Michoacán de Ocampo              Juárez               Benito Juárez     87
Tlaxcala                         Benito Juárez        Benito Juárez     20
Puebla                           Los Reyes de Juárez  Benito Juárez     12
Chihuahua                        Namiquipa            Benito Juárez      7
Name: count, dtype: int64

Está correcto. Hay muchas comunidades que se llaman Benito Juárez, deben de tener diferente municipio

In [21]:
localidades_to_drop = ["loc_regis", "loc_resid", "loc_ocurr", "loc_ocules"]
columns_to_drop += localidades_to_drop

## SEXO

> Igual  que https://github.com/mar-esther23/CursoPython_DefuncionesCOVID19enMexico/blob/main/EDR4_Limpieza.ipynb solo cambié .replace por .map

In [22]:
# Definir el diccionario de mapeo para la columna sexo
mapeo_sexo = { 1:'Hombre', 2:'Mujer', 9:'No especificado' }
year_data_fixed["sexo"] = year_data["sexo"].map(mapeo_sexo)

year_data_fixed['sexo'].value_counts(dropna=False)

sexo
Hombre             458266
Mujer              360814
No especificado       592
Name: count, dtype: int64

In [23]:
year_data_fixed['sexo'] = year_data_fixed['sexo'].astype('category')
year_data_fixed['sexo']

0                  Hombre
1                  Hombre
2                  Hombre
3                  Hombre
4                   Mujer
               ...
819667    No especificado
819668              Mujer
819669              Mujer
819670              Mujer
819671              Mujer
Name: sexo, Length: 819672, dtype: category
Categories (3, str): ['Hombre', 'Mujer', 'No especificado']

## EDAD

In [24]:
# Definimos la función especial
def modify_age_inegi(number):
    if number == 4998:
        return np.nan
    elif number < 4000:
        return 0
    else:
        return number - 4000

# Aplicar la función a la columna 'EDAD' y crear una nueva columna 'EDAD_ANOS'
year_data_fixed['edad'] = year_data_fixed['edad'].apply(modify_age_inegi)

# Mostrar los valores únicos de la nueva columna para verificar el cambio
year_data_fixed['edad'].value_counts(dropna=False).sort_index()
year_data_fixed['edad'] = year_data_fixed['edad'].astype('Int64')

## EDAD AGRUPADA
Será útil para generar nombres

In [25]:
# igual que el curso
from pandas.api.types import CategoricalDtype
# Construir el catálogo
mapeo_edad_agru = {
                    1:'Menores de un año', 2:'De un año', 3:'De 2', 4:'De 3', 5:'De 4', 6:'De 5 a 9',
                    7:'De 10 a 14', 8:'De 15 a 19', 9:'De 20 a 24', 10:'De 25 a 29', 11:'De 30 a 34',
                    12:'De 35 a 39', 13:'De 40 a 44', 14:'De 45 a 49', 15:'De 50 a 54', 16:'De 55 a 59',
                    17:'De 60 a 64', 18:'De 65 a 69', 19:'De 70 a 74', 20:'De 75 a 79', 21:'De 80 a 84',
                    22:'De 85 a 89', 23:'De 90 a 94', 24:'De 95 a 99', 25:'De 100 a 104', 26:'De 105 a 109',
                    27:'De 110 a 114', 28:'De 115 a 119', 29:'De 120 y más', 30:'No especificada'
                  }
# Aplicar el reemplazo en la columna 'edad_agru'
year_data_fixed['edad_agru'] = year_data['edad_agru'].replace(mapeo_edad_agru)
# Generar la categoría ordenada, usamos los valores del diccionario
cat_edad_agru = CategoricalDtype(categories=mapeo_edad_agru.values(), ordered=True)
# Convertir a la columna a la categoría ordenada
year_data_fixed['edad_agru'] = year_data_fixed['edad_agru'].astype(cat_edad_agru)
# Mostrar el conteo de valores únicos para verificar el cambio
year_data_fixed['edad_agru'].value_counts().sort_index()

edad_agru
Menores de un año    17421
De un año             1663
De 2                   905
De 3                   616
De 4                   595
De 5 a 9              2425
De 10 a 14            3329
De 15 a 19            9701
De 20 a 24           14723
De 25 a 29           17381
De 30 a 34           20769
De 35 a 39           22259
De 40 a 44           26970
De 45 a 49           35118
De 50 a 54           45233
De 55 a 59           54749
De 60 a 64           66875
De 65 a 69           76118
De 70 a 74           79988
De 75 a 79           84340
De 80 a 84           83905
De 85 a 89           75030
De 90 a 94           50086
De 95 a 99           19846
De 100 a 104          4588
De 105 a 109           449
De 110 a 114            53
De 115 a 119            11
De 120 y más             4
No especificada       4522
Name: count, dtype: int64

## FECHAS

In [26]:
fechas = {
    "fecha_ocurr": ["dia_ocurr", "mes_ocurr", "anio_ocur", "horas", "minutos"],
    "fecha_regis": ["dia_regis", "mes_regis", "anio_regis"],
    "fecha_nacim": ["dia_nacim", "mes_nacim", "anio_nacim"],
    "fecha_cert":  ["dia_cert",  "mes_cert",  "anio_cert"],
}

for fecha_col, date_parts in fechas.items():
    d, m, y = date_parts[0], date_parts[1], date_parts[2]

    # Centinelas → NaN
    year_data_fixed[d] = year_data_fixed[d].replace(99, np.nan)
    year_data_fixed[m] = year_data_fixed[m].replace(99, np.nan)
    year_data_fixed[y] = year_data_fixed[y].replace(9999, np.nan)

    if len(date_parts) == 5:
        h, mi = date_parts[3], date_parts[4]
        year_data_fixed[h]  = year_data_fixed[h].replace([98, 99], np.nan)
        year_data_fixed[mi] = year_data_fixed[mi].replace([98, 99], np.nan)
        year_data_fixed[h]  = year_data_fixed[h].fillna(0)
        year_data_fixed[mi] = year_data_fixed[mi].fillna(0)

        data_time = year_data_fixed[date_parts].rename(columns={
            d: "day", m: "month", y: "year", h: "hour", mi: "minute",
        })
    else:
        data_time = year_data_fixed[date_parts].rename(columns={
            d: "day", m: "month", y: "year",
        })

    # sin astype, pd.to_datetime maneja floats con NaN
    year_data_fixed[fecha_col] = pd.to_datetime(data_time, errors="coerce")

    display(year_data_fixed[[*date_parts, fecha_col]].tail())
    columns_to_drop += date_parts

        dia_ocurr  mes_ocurr  anio_ocur  horas  minutos         fecha_ocurr
819667       16.0        2.0     2024.0    0.0      0.0 2024-02-16 00:00:00
819668        4.0        1.0     2024.0   16.0     40.0 2024-01-04 16:40:00
819669       28.0       11.0     2024.0   10.0     33.0 2024-11-28 10:33:00
819670        6.0        1.0     2024.0   14.0     27.0 2024-01-06 14:27:00
819671       29.0       12.0     2024.0    0.0      0.0 2024-12-29 00:00:00

        dia_regis  mes_regis  anio_regis fecha_regis
819667       16.0          2        2024  2024-02-16
819668        4.0          1        2024  2024-01-04
819669       28.0         11        2024  2024-11-28
819670        6.0          1        2024  2024-01-06
819671       29.0         12        2024  2024-12-29

        dia_nacim  mes_nacim  anio_nacim fecha_nacim
819667        NaN        NaN         NaN         NaT
819668       21.0        3.0      1990.0  1990-03-21
819669       14.0        2.0      2008.0  2008-02-14
819670        1.0        9.0      1949.0  1949-09-01
819671       25.0        5.0      1988.0  1988-05-25

        dia_cert  mes_cert  anio_cert fecha_cert
819667      16.0       2.0       2024 2024-02-16
819668       4.0       1.0       2024 2024-01-04
819669      28.0      11.0       2024 2024-11-28
819670       6.0       1.0       2024 2024-01-06
819671      30.0      12.0       2024 2024-12-30

In [27]:
year_data_fixed[['fecha_ocurr', 'fecha_regis', 'fecha_nacim']].info()

<class 'pandas.DataFrame'>
RangeIndex: 819672 entries, 0 to 819671
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   fecha_ocurr  818965 non-null  datetime64[us]
 1   fecha_regis  770189 non-null  datetime64[us]
 2   fecha_nacim  809625 non-null  datetime64[us]
dtypes: datetime64[us](3)
memory usage: 18.8 MB

## RESTO DE CAMPOS

In [28]:
# Ver todos los campos del diccionario con su catálogo asociado
data_dictionary[['NEMONICO', 'NOMBRE_CAMPO', 'CATALOGO']]

,NEMONICO,NOMBRE_CAMPO,CATALOGO
0,ent_regis,Entidad de registro,entidad_municipio_localidad_2024
1,mun_regis,Municipio o demarcación territorial de registro,entidad_municipio_localidad_2024
2,tloc_regis,Tamaño de localidad de registro,tamaño_localidad
3,loc_regis,Localidad de registro,entidad_municipio_localidad_2024
4,ent_resid,Entidad de residencia habitual del (la) fallec...,entidad_municipio_localidad_2024
...,...,...,...
69,ent_ocules,Entidad de ocurrencia de la lesión,entidad_municipio_localidad_2024
70,mun_ocules,Municipio o demarcación territorial de ocurren...,entidad_municipio_localidad_2024
71,loc_ocules,Localidad de ocurrencia de la lesión,entidad_municipio_localidad_2024
72,razon_m,Defunciones para calcular la razón de la morta...,razon_materna
73,dis_re_oax,Distritos de registro de Oaxaca,entidad_municipio_localidad_2024

In [29]:
import unicodedata

def _normalizar_nombre_col(col):
    # quitar acentos y pasar a minúsculas
    col = str(col).strip().lower()
    col = unicodedata.normalize("NFKD", col).encode("ascii", "ignore").decode("ascii")
    return col


def cargar_catalogo(nombre_catalogo, year_datapath=YEAR_DATAPATH):
    """
    Carga un catálogo del INEGI por nombre (sin .csv).
    - Repara mojibake en columnas string.
    - Normaliza nombres de columnas a lowercase (sin acentos/espacios).
    """
    catalogo_path = year_datapath / "catalogos" / f"{nombre_catalogo}.csv"
    df_cat = pd.read_csv(catalogo_path, low_memory=False)


    # reparar mojibake en columnas string
    for col in df_cat.select_dtypes(include=["object", "str"]).columns:
        df_cat[col] = df_cat[col].map(reparar_mojibake)
        
    # renombrar columnas a lowercase normalizado
    df_cat.columns = [_normalizar_nombre_col(c) for c in df_cat.columns]

    return df_cat

In [30]:
# Ejemplo: inspeccionar el catálogo de sexo
cat = cargar_catalogo("sexo")
display(cat.head(20))
print(cat.columns.tolist())
print(cat.shape)

   cve          descrip
0    1           Hombre
1    2            Mujer
2    9  No especificado

['cve', 'descrip']
(3, 2)

In [31]:
def manual_fixes(df, col, cat):
    """
    Aplica correcciones manuales a los DataFrames según la columna a decodificar.
    """
    if col == "lista1":
        # Convertir a Int64 para manejar NaN
        df[col] = df[col].astype("Int64")
        cat.iloc[:, 0] = cat.iloc[:, 0].astype("Int64")
    elif col == "gr_lismex":
        # Asegurar que los códigos tengan dos dígitos con ceros a la izquierda
        df[col] = df[col].astype(str).str.zfill(2)
        cat.iloc[:, 0] = cat.iloc[:, 0].astype(str).str.zfill(2)
    return cat, df

def decodificar_normal(df, col, nombre_catalogo, col_clave=None, col_valor=None):
    """
    Decodifica una columna usando un catálogo.
    - df: DataFrame
    - col: nombre de la columna a decodificar (ej. 'sexo')
    - nombre_catalogo: nombre del catálogo sin .csv
    - col_clave: columna del catálogo con la clave (autodetecta si None)
    - col_valor: columna del catálogo con el valor legible (autodetecta si None)
    
    Retorna el df con una nueva columna '<col>_nom'.
    """
    cat = cargar_catalogo(nombre_catalogo)

    cat, df = manual_fixes(df, col, cat)
    
    # Autodetectar columnas: la clave suele ser la primera, el valor la última
    if col_clave is None:
        col_clave = cat.columns[0]
    if col_valor is None:
        try:
            col_valor = next(c for c in cat.columns if c.lower() == "descrip")
        except KeyError:
            col_valor = cat.columns[-1]
    print(f"    col_clave: {col_clave}, col_valor: {col_valor}")
    
    # Asegurar tipos compatibles
    cat[col_clave] = cat[col_clave].astype(str)
    df[col] = df[col].astype(str)
    df[col] = df[col].str.strip()
    
    mapeo = dict(zip(cat[col_clave], cat[col_valor]))
    df[f"{col}_nom"] = df[col].map(mapeo)
    return df

In [32]:
    # Nombres de catálogo 
campos_simples = {
    "edo_civil":   "estado_civil",
    "escolarida":  "escolaridad",
    "ocupacion":   "ocupacion",
    "cond_act":    "condicion_actividad",
    "nacionalid":  "nacionalidad",
    "tipo_defun":  "presunta_defuncion_violenta",
    "lugar_ocur":  "lugar_ocurrencia",
    "causa_def":     "causa_defuncion",
    "sitio_ocur":  "sitio_ocurrencia",
    "cond_cert":   "certificante",
    "derechohab":  "derechohabiencia",
    "embarazo":    "condicion_embarazo",
    "rel_emba":    "relacion_con_embarazo",
    "par_agre":    "parentesco_agresor",
    "vio_fami":    "violencia_familiar",
    "asist_medi":  "asistencia_medica",
    "cirugia":     "cirugia",
    "natviole":    "accidental_violenta",
    "necropsia":   "necropsia",
    "usonecrops":  "uso_necropsia",
    "encefalica":  "encefalica",
    "donador":     "donador",
    "ocurr_trab":  "ocurrio_trabajo",
    "afromex":     "afromexi",
    "conindig":    "conind",
    "lengua":      "lengua_indigena",
    "cve_lengua":  "lenguas",
    "nacesp_cve":  "paises",
    "sem_gest": "edadgest",
    "maternas": "causa_defuncion",
    "razon_m": "razon_materna",
    "complicaro":  "complicaron_embarazo",
    "area_ur":     "area_urbana_rural",
    "tloc_regis":  "tamaño_localidad",
    "tloc_resid":  "tamaño_localidad",
    "tloc_ocurr":  "tamaño_localidad",
    "lista1": "lista1",
    "gr_lismex": "grupo_lista_mexicana",
    "lista_mex": "lista_mexicana",
    "cod_adicio": "codigo_adicional"
}

for col, cat_name in campos_simples.items():
    try:
        print(f"✓ {col} -> {cat_name}")
        year_data_fixed = decodificar_normal(year_data_fixed, col, cat_name)
        print(f"{year_data_fixed[f"{col}_nom"].isna().sum()}  en {col}_nom")
        columns_to_drop.append(col)
    except FileNotFoundError:
        print(f"✗ {col}: catálogo '{cat_name}' no encontrado")

✓ edo_civil -> estado_civil
    col_clave: cve, col_valor: descrip
0  en edo_civil_nom
✓ escolarida -> escolaridad
    col_clave: cve, col_valor: descrip
0  en escolarida_nom
✓ ocupacion -> ocupacion
    col_clave: cve, col_valor: descrip
0  en ocupacion_nom
✓ cond_act -> condicion_actividad
    col_clave: cve, col_valor: descrip
0  en cond_act_nom
✓ nacionalid -> nacionalidad
    col_clave: cve, col_valor: descrip
0  en nacionalid_nom
✓ tipo_defun -> presunta_defuncion_violenta
    col_clave: cve, col_valor: descrip
0  en tipo_defun_nom
✓ lugar_ocur -> lugar_ocurrencia
    col_clave: cve, col_valor: descrip
0  en lugar_ocur_nom
✓ causa_def -> causa_defuncion
    col_clave: clave, col_valor: descrip
0  en causa_def_nom
✓ sitio_ocur -> sitio_ocurrencia
    col_clave: cve, col_valor: descrip
0  en sitio_ocur_nom
✓ cond_cert -> certificante
    col_clave: cve, col_valor: descrip
0  en cond_cert_nom
✓ derechohab -> derechohabiencia
    col_clave: cve, col_valor: descrip
0  en derechohab_nom
✓ embarazo -> condicion_embarazo
    col_clave: cve, col_valor: descrip
0  en embarazo_nom
✓ rel_emba -> relacion_con_embarazo
    col_clave: cve, col_valor: descrip
0  en rel_emba_nom
✓ par_agre -> parentesco_agresor
    col_clave: cve, col_valor: descrip
0  en par_agre_nom
✓ vio_fami -> violencia_familiar
    col_clave: cve, col_valor: descrip
0  en vio_fami_nom
✓ asist_medi -> asistencia_medica
    col_clave: cve, col_valor: descrip
0  en asist_medi_nom
✓ cirugia -> cirugia
    col_clave: cve, col_valor: descrip
0  en cirugia_nom
✓ natviole -> accidental_violenta
    col_clave: cve, col_valor: descrip
0  en natviole_nom
✓ necropsia -> necropsia
    col_clave: cve, col_valor: descrip
0  en necropsia_nom
✓ usonecrops -> uso_necropsia
    col_clave: cve, col_valor: descrip
0  en usonecrops_nom
✓ encefalica -> encefalica
    col_clave: cve, col_valor: descrip
0  en encefalica_nom
✓ donador -> donador
    col_clave: cve, col_valor: descrip
0  en donador_nom
✓ ocurr_trab -> ocurrio_trabajo
    col_clave: cve, col_valor: descrip
0  en ocurr_trab_nom
✓ afromex -> afromexi
    col_clave: cve, col_valor: descrip
0  en afromex_nom
✓ conindig -> conind
    col_clave: cve, col_valor: descrip
0  en conindig_nom
✓ lengua -> lengua_indigena
    col_clave: cve, col_valor: descrip
0  en lengua_nom
✓ cve_lengua -> lenguas
    col_clave: clave, col_valor: descrip
0  en cve_lengua_nom
✓ nacesp_cve -> paises
    col_clave: cve, col_valor: descrip
0  en nacesp_cve_nom
✓ sem_gest -> edadgest
    col_clave: cve, col_valor: descrip
0  en sem_gest_nom
✓ maternas -> causa_defuncion
    col_clave: clave, col_valor: descrip
818910  en maternas_nom
✓ razon_m -> razon_materna
    col_clave: cve, col_valor: descrip
819104  en razon_m_nom
✓ complicaro -> complicaron_embarazo
    col_clave: cve, col_valor: descrip
0  en complicaro_nom
✓ area_ur -> area_urbana_rural
    col_clave: cve, col_valor: descrip
0  en area_ur_nom
✓ tloc_regis -> tamaño_localidad
    col_clave: cve, col_valor: descrip
0  en tloc_regis_nom
✓ tloc_resid -> tamaño_localidad
    col_clave: cve, col_valor: descrip
0  en tloc_resid_nom
✓ tloc_ocurr -> tamaño_localidad
    col_clave: cve, col_valor: descrip
0  en tloc_ocurr_nom
✓ lista1 -> lista1
    col_clave: cve, col_valor: descrip
1436  en lista1_nom
✓ gr_lismex -> grupo_lista_mexicana
    col_clave: cve, col_valor: descrip
0  en gr_lismex_nom
✓ lista_mex -> lista_mexicana
    col_clave: cve, col_valor: descrip
3012  en lista_mex_nom
✓ cod_adicio -> codigo_adicional
    col_clave: cve, col_valor: descrip
733472  en cod_adicio_nom

#### Columnas que tienen muchos Nans

In [33]:
columms_to_check = ["maternas", "razon_m", "lista1", "lista_mex"]
columms_to_check = ["cod_adicio"]

for col in columms_to_check:
    print(f"Nulos en {col}: {year_data_fixed[f'{col}'].isna().sum()}")
    display(year_data_fixed[col].value_counts(dropna=False))
    cat = cargar_catalogo(campos_simples[col])
    display(cat.head(20))

# no aparecen en el catalogo
year_data_fixed[year_data_fixed["lista_mex_nom"].isna()][["lista_mex", "lista_mex_nom"]].value_counts(dropna=False).sort_index()
year_data_fixed[year_data_fixed["cod_adicio_nom"].isna()][["cod_adicio", "cod_adicio_nom"]].value_counts(dropna=False).sort_index()

Nulos en cod_adicio: 0

cod_adicio
0000    733471
S069     15318
T71X     11504
S219      5438
S062      5076
         ...
T143         1
T392         1
T449         1
T475         1
T881         1
Name: count, Length: 604, dtype: int64

     cve                                            descrip
0   A505  OTRAS FORMAS DE SIFILIS CONGENITA TARDIA, SINT...
1   D77X  OTROS TRASTORNOS DE LA SANGRE Y DE LOS ORGANOS...
2   E351  TRASTORNOS DE LAS GLANDULAS SUPRARRENALES EN E...
3   F000  DEMENCIA EN LA ENFERMEDAD DE ALZHEIMER, DE COM...
4   F001  DEMENCIA EN LA ENFERMEDAD DE ALZHEIMER, DE COM...
5   F002  DEMENCIA EN LA ENFERMEDAD DE ALZHEIMER, ATIPIC...
6   F009  DEMENCIA EN LA ENFERMEDAD DE ALZHEIMER, NO ESP...
7   F020                  DEMENCIA EN LA ENFERMEDAD DE PICK
8   F021     DEMENCIA EN LA ENFERMEDAD DE CREUTZFELDT-JAKOB
9   F022            DEMENCIA EN LA ENFERMEDAD DE HUNTINGTON
10  F023             DEMENCIA EN LA ENFERMEDAD DE PARKINSON
11  F028  DEMENCIA EN OTRAS ENFERMEDADES ESPECIFICADAS C...
12  F042  SINDROME AMNESICO ORGANICO, NO INDUCIDO POR AL...
13  G01X  MENINGITIS EN ENFERMEDADES BACTERIANAS CLASIFI...
14  G020  MENINGITIS EN ENFERMEDADES VIRALES CLASIFICADA...
15  G021                              MENINGITIS EN MICOSIS
16  G050  ENCEFALITIS, MIELITIS Y ENCEFALOMIELITIS EN EN...
17  G051  ENCEFALITIS, MIELITIS Y ENCEFALOMIELITIS EN EN...
18  G052  ENCEFALITIS, MIELITIS Y ENCEFALOMIELITIS EN OT...
19  G07X  ABSCESO Y GRANULOMA INTRACRANEAL E INTRARRAQUI...

cod_adicio  cod_adicio_nom
0000        NaN               733471
F100        NaN                    1
Name: count, dtype: int64

## CAUSA DE DEFUNCIÓN (DETALLES)
Son referencias a niveles de agregación de la CIE-10, capítulo-grupo al igual que entidad-municipio tienen mapeo jerárquíco

In [34]:
df_catalogo = cargar_catalogo("capitulo_grupo")
# el csv de capitulo grupo en vez de tener 0 en el  en el primer grupo de cada capitulo está vacío
# fill nan en columna grupo con el valor 0
df_catalogo["gpo"] = df_catalogo["gpo"].fillna(0)
df_catalogo["gpo"] = df_catalogo["gpo"].astype(int)
df_catalogo.head()

   cap  gpo                                          descrip
0    1    0  Ciertas enfermedades infecciosas y parasitarias
1    1    1  Enfermedades infecciosas intestinales (A00-A09)
2    1    2                          Tuberculosis  (A15-A19)
3    1    3           Ciertas zoonosis bacterianas (A20-A28)
4    1    4         Otras enfermedades bacterianas (A30-A49)

In [35]:
mapeo_cap_gpo = df_catalogo.rename(columns={
    "cap":   "capitulo",
    "gpo":   "grupo",
    "descrip": "grupo_nom"
})

# Asegurar mismo tipo en las claves de ambos lados
year_data_fixed["capitulo"] = year_data_fixed["capitulo"].astype(str)
year_data_fixed["grupo"]    = year_data_fixed["grupo"].astype(str)
mapeo_cap_gpo["capitulo"]   = mapeo_cap_gpo["capitulo"].astype(str)
mapeo_cap_gpo["grupo"]      = mapeo_cap_gpo["grupo"].astype(str)

# Merge jerárquico por clave compuesta (capitulo, grupo)
year_data_fixed = pd.merge(
    year_data_fixed,
    mapeo_cap_gpo[["capitulo", "grupo", "grupo_nom"]],
    on=["capitulo", "grupo"],
    how="left"
)
display(year_data_fixed[["capitulo", "grupo", "grupo_nom"]].isna().sum())
year_data_fixed[["capitulo", "grupo", "grupo_nom"]].value_counts(dropna=False).sort_index()

capitulo     0
grupo        0
grupo_nom    0
dtype: int64

capitulo  grupo  grupo_nom
1         1      Enfermedades infecciosas intestinales (A00-A09)                                                             3394
          10     Fiebres virales transmitidas por artrópodos y fiebres virales hemorrágicas (A90-A99)                        1198
          11     Infecciones virales caracterizadas por lesiones de la piel y de las membranas mucosas (B00-B09)               84
          12     Hepatitis viral (B15-B19)                                                                                    658
          13     Enfermedad por virus de la inmunodeficiencia humana (VIH) (B20-B24)                                         5149
                                                                                                                            ...
9         5      Enfermedad cardiopulmonar y enfermedades de la circulación pulmonar (I26-I28)                               2985
          6      Otras formas de enfermedad del corazón (I30-I52)                                                           16931
          7      Enfermedades cerebrovasculares (I60-I69)                                                                   34784
          8      Enfermedades de las arterias, de las arteriolas y de los vasos capilares (I70-I79)                          2497
          9      Enfermedades de las venas y de los vasos y ganglios linfáticos, no clasificadas en otra parte (I80-I89)     1921
Name: count, Length: 210, dtype: int64

## DIS RE OAX

In [36]:
# dis_re_oax usa el mismo catálogo entidad_municipio_localidad_2024 con mapeo jerárquico
# cve_mun (901-930) para cve_ent == 20 renombrada a "ent_code", 
df_catalogo = cargar_catalogo("entidad_municipio_localidad_2024")
cat_distritos_oax = (
    df_catalogo
    .loc[(df_catalogo['cve_ent'] == 20) &
         (df_catalogo['cve_mun'].between(901, 930)) &
         (df_catalogo['cve_loc'] == 0),
         ['cve_mun', 'nom_loc']]
    .drop_duplicates(subset='cve_mun')
)

mapeo_oax = dict(zip(cat_distritos_oax['cve_mun'], cat_distritos_oax['nom_loc']))
mapeo_oax[999] = "Distrito no especificado"

year_data_fixed['dis_re_oax_nom'] = year_data_fixed['dis_re_oax'].map(mapeo_oax)
year_data_fixed['dis_re_oax_nom'].isna().sum()
columns_to_drop.append('dis_re_oax')

# Drop Columns and save

In [37]:
# drop columns that are no longer needed
year_data_fixed.drop(columns=columns_to_drop, inplace=True)
year_data_fixed.columns

Index(['sexo', 'edad', 'gramos', 'capitulo', 'grupo', 'edad_agru',
       'ent_regis_nom', 'ent_resid_nom', 'ent_ocurr_nom', 'ent_nac_nom',
       'ent_ocules_nom', 'mun_regis_nom', 'mun_resid_nom', 'mun_ocurr_nom',
       'mun_ocules_nom', 'loc_regis_nom', 'loc_resid_nom', 'loc_ocurr_nom',
       'loc_ocules_nom', 'fecha_ocurr', 'fecha_regis', 'fecha_nacim',
       'fecha_cert', 'edo_civil_nom', 'escolarida_nom', 'ocupacion_nom',
       'cond_act_nom', 'nacionalid_nom', 'tipo_defun_nom', 'lugar_ocur_nom',
       'causa_def_nom', 'sitio_ocur_nom', 'cond_cert_nom', 'derechohab_nom',
       'embarazo_nom', 'rel_emba_nom', 'par_agre_nom', 'vio_fami_nom',
       'asist_medi_nom', 'cirugia_nom', 'natviole_nom', 'necropsia_nom',
       'usonecrops_nom', 'encefalica_nom', 'donador_nom', 'ocurr_trab_nom',
       'afromex_nom', 'conindig_nom', 'lengua_nom', 'cve_lengua_nom',
       'nacesp_cve_nom', 'sem_gest_nom', 'maternas_nom', 'razon_m_nom',
       'complicaro_nom', 'area_ur_nom', 'tloc_regis_nom', 'tloc_resid_nom',
       'tloc_ocurr_nom', 'lista1_nom', 'gr_lismex_nom', 'lista_mex_nom',
       'cod_adicio_nom', 'grupo_nom', 'dis_re_oax_nom'],
      dtype='str')

In [38]:
#! pip uninstall pyarrow -y
#! pip install pyarrow

In [39]:
import pyarrow 

OUTPUTPATH.mkdir(parents=True, exist_ok=True)
year_data_fixed.to_parquet(OUTPUTPATH / f"edr_{year}_limpio.parquet", index=False)
print(f"Guardado: {year_data_fixed.shape}")

Guardado: (819672, 65)