Fuente:
Datos abiertos  de SEGSOCIAL	IMSS-BIENESTAR	S038 / S038	10,773,410 registros JULIO - SEPTIEMBRE 2025
Página: https://pub.bienestar.gob.mx/pub/personas
Archivo: https://pub.bienestar.gob.mx/data/v2/last/S038/257_259/Programa_S038_S038_257_259.zip

In [2]:
from pathlib import Path
import sys

PROJECT_PATH = Path("/Users/daragama/Documents/Master25/Tesis/datos_semisinteticos/")
DATAPATH = PROJECT_PATH  / "data"
OUTPUTPATH = PROJECT_PATH / "output"
print(f"DATAPATH: {DATAPATH}")

sys.path.append(str(Path.cwd().parent))

DATAPATH: /Users/daragama/Documents/Master25/Tesis/datos_semisinteticos/data

# DATOS

In [3]:
# read all csv files in the data folder
import pandas as pd


raw_datapath = DATAPATH / "raw" / "datos_bienestar"
csv_files = list(raw_datapath.glob("*.csv"))

# crear un df con todos los csv files
df_nombres = pd.concat([pd.read_csv(f, encoding="latin-1", low_memory=False) for f in csv_files], ignore_index=True)

In [4]:
df_nombres.info()

<class 'pandas.DataFrame'>
RangeIndex: 10773422 entries, 0 to 10773421
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   NUM.               str
 1   CVE_ENTIDAD        float64
 2   CVE_MUNICIPIO      float64
 3   PRIMER APELLIDO    str
 4   SEGUNDO APELLIDO   str
 5   NOMBRE             str
 6   SEXO               str
 7   EDAD               str
 8   FECHA ALTA         str
 9   IMPORTE BENEFICIO  float64
dtypes: float64(3), str(7)
memory usage: 1.3 GB

In [5]:
# buscar registros con CVE_ENTIDAD, NOMBRE, PRIMER APELLIDO, SEGUNDO APELLIDO y EDAD vacíos
empties = df_nombres[df_nombres[["SEXO", "NOMBRE", "PRIMER APELLIDO", "SEGUNDO APELLIDO", "EDAD"]].isnull().all(axis=1)]
# eliminar estos registros
df_nombres = df_nombres.drop(empties.index)

df_nombres.isnull().sum()

NUM.                   0
CVE_ENTIDAD            0
CVE_MUNICIPIO          0
PRIMER APELLIDO      441
SEGUNDO APELLIDO      20
NOMBRE                 0
SEXO                   0
EDAD                   0
FECHA ALTA             0
IMPORTE BENEFICIO      0
dtype: int64

# Quitar MENOR

In [6]:
# menores tiene MENOR en todos los campos
df_nombres = df_nombres[df_nombres["EDAD"] != "MENOR"]

# Fix datatypes

In [7]:
# fix data types
df_nombres["NUM."] = df_nombres["NUM."].astype(float).astype(int)
# nans in CVE_ENTIDAD set to 99
df_nombres["CVE_ENTIDAD"] = df_nombres["CVE_ENTIDAD"].fillna(99)
df_nombres["CVE_ENTIDAD"] = df_nombres["CVE_ENTIDAD"].astype(int)
# nans in CVE_MUNICIPIO set to 999
df_nombres["CVE_MUNICIPIO"] = df_nombres["CVE_MUNICIPIO"].fillna(999)
df_nombres["CVE_MUNICIPIO"] = df_nombres["CVE_MUNICIPIO"].astype(int)

df_nombres.head()

,NUM.,CVE_ENTIDAD,CVE_MUNICIPIO,PRIMER APELLIDO,SEGUNDO APELLIDO,NOMBRE,SEXO,EDAD,FECHA ALTA,IMPORTE BENEFICIO
1,5047,24,24032,ROMERO,MARTINEZ,JOSE GUADALUPE,MASCULINO,34,05-05-2015,0.0
2,5048,24,24032,ROMERO,MENDOZA,MANUELA,FEMENINO,65,05-05-2015,0.0
3,5049,24,24032,PADRON,SANCHEZ,JUAN,MASCULINO,94,05-05-2015,0.0
4,5050,24,24032,AGUILAR,CARDENAS,BENITA,FEMENINO,63,05-05-2015,0.0
5,5051,24,24032,BORJAS,MARTINEZ,GABRIELA,FEMENINO,60,05-05-2015,0.0

# EDAD

In [8]:
df_nombres.value_counts("EDAD")

EDAD
18     235851
19     230066
20     229151
21     226459
22     223560
        ...
96       4344
97       3538
98       2924
99       2739
100         5
Name: count, Length: 84, dtype: int64

In [9]:
bins = [14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64,
        69, 74, 79, 84, 89, 94, 99, 104, 109, 114, 119, float("inf")]

labels = [
    "De 15 a 19", "De 20 a 24", "De 25 a 29", "De 30 a 34",
    "De 35 a 39", "De 40 a 44", "De 45 a 49", "De 50 a 54",
    "De 55 a 59", "De 60 a 64", "De 65 a 69", "De 70 a 74",
    "De 75 a 79", "De 80 a 84", "De 85 a 89", "De 90 a 94",
    "De 95 a 99", "De 100 a 104", "De 105 a 109", "De 110 a 114",
    "De 115 a 119", "De 120 y más"
]

edad_num = pd.to_numeric(df_nombres["EDAD"], errors="coerce")

df_nombres["EDAD_AGRUPADA"] = pd.cut(
    edad_num,
    bins=bins,
    labels=labels,
    right=True
)

df_nombres.head()

,NUM.,CVE_ENTIDAD,CVE_MUNICIPIO,PRIMER APELLIDO,SEGUNDO APELLIDO,NOMBRE,SEXO,EDAD,FECHA ALTA,IMPORTE BENEFICIO,EDAD_AGRUPADA
1,5047,24,24032,ROMERO,MARTINEZ,JOSE GUADALUPE,MASCULINO,34,05-05-2015,0.0,De 30 a 34
2,5048,24,24032,ROMERO,MENDOZA,MANUELA,FEMENINO,65,05-05-2015,0.0,De 65 a 69
3,5049,24,24032,PADRON,SANCHEZ,JUAN,MASCULINO,94,05-05-2015,0.0,De 90 a 94
4,5050,24,24032,AGUILAR,CARDENAS,BENITA,FEMENINO,63,05-05-2015,0.0,De 60 a 64
5,5051,24,24032,BORJAS,MARTINEZ,GABRIELA,FEMENINO,60,05-05-2015,0.0,De 60 a 64

# REGION

In [10]:
from mx_nombres.map_regiones import agregar_region

agregar_region(df_nombres, columna_entidad="CVE_ENTIDAD", columna_region="region8", modelo=8, inplace=True)
agregar_region(df_nombres, columna_entidad="CVE_ENTIDAD", columna_region="region5", modelo=5, inplace=True)

,NUM.,CVE_ENTIDAD,CVE_MUNICIPIO,PRIMER APELLIDO,SEGUNDO APELLIDO,NOMBRE,SEXO,EDAD,FECHA ALTA,IMPORTE BENEFICIO,EDAD_AGRUPADA,region8,region5
1,5047,24,24032,ROMERO,MARTINEZ,JOSE GUADALUPE,MASCULINO,34,05-05-2015,0.0,De 30 a 34,Centronorte,Centro Occidente
2,5048,24,24032,ROMERO,MENDOZA,MANUELA,FEMENINO,65,05-05-2015,0.0,De 65 a 69,Centronorte,Centro Occidente
3,5049,24,24032,PADRON,SANCHEZ,JUAN,MASCULINO,94,05-05-2015,0.0,De 90 a 94,Centronorte,Centro Occidente
4,5050,24,24032,AGUILAR,CARDENAS,BENITA,FEMENINO,63,05-05-2015,0.0,De 60 a 64,Centronorte,Centro Occidente
5,5051,24,24032,BORJAS,MARTINEZ,GABRIELA,FEMENINO,60,05-05-2015,0.0,De 60 a 64,Centronorte,Centro Occidente
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10773415,21377,7,7065,PEÑATE,MENDEZ,OCTAVIO,MASCULINO,29,20-08-2013,0.0,De 25 a 29,Suroeste,Sureste
10773416,21378,7,7065,PEÑATE,SANCHEZ,BELINDA ANAYELI,FEMENINO,21,20-08-2013,0.0,De 20 a 24,Suroeste,Sureste
10773417,21379,7,7065,VAZQUEZ,CRUZ,ANATALIA,FEMENINO,47,20-08-2013,0.0,De 45 a 49,Suroeste,Sureste
10773419,21381,7,7065,PEREZ,AGUILAR,VIDAURA,FEMENINO,35,20-08-2013,0.0,De 35 a 39,Suroeste,Sureste
10773420,21382,7,7065,LOPEZ,MARTINEZ,SANDRA,FEMENINO,26,22-04-2016,0.0,De 25 a 29,Suroeste,Sureste

In [ ]:
df_nombres
df_nombres.to_parquet(OUTPUTPATH / "df_nombres.parquet", compression='zstd', compression_level=22, index=False)

# NOMBRES

In [12]:
# unique nombres por edad agrupada
# por entidad (bolsas pequeñas)
df_agrupado_nombre = (
    df_nombres
    .groupby(["EDAD_AGRUPADA", "CVE_ENTIDAD", "SEXO", "NOMBRE"])
    .size()
    .reset_index(name="CONTEO")
)
size_df_agrupado = df_agrupado_nombre.shape[0]
df_agrupado_nombre = df_agrupado_nombre[df_agrupado_nombre["CONTEO"] > 2]
print(f"Se eliminaron {size_df_agrupado - df_agrupado_nombre.shape[0]} registros con conteo menor o igual a 2.")

# por region5 (bolsas grandes)
df_agrupado_nombre_region5 = (
    df_nombres
    .groupby(["EDAD_AGRUPADA", "region5", "SEXO", "NOMBRE"])
    .size()
    .reset_index(name="CONTEO")
)
size_df_agrupado = df_agrupado_nombre_region5.shape[0]
df_agrupado_nombre_region5 = df_agrupado_nombre_region5[df_agrupado_nombre_region5["CONTEO"] > 2]
print(f"Se eliminaron {size_df_agrupado - df_agrupado_nombre_region5.shape[0]} registros con conteo menor o igual a 2.")

# por region8 (bolsas medianas)
df_agrupado_nombre_region8 = (
    df_nombres
    .groupby(["EDAD_AGRUPADA", "region8", "SEXO", "NOMBRE"])
    .size()
    .reset_index(name="CONTEO")
)
size_df_agrupado = df_agrupado_nombre_region8.shape[0]
df_agrupado_nombre_region8 = df_agrupado_nombre_region8[df_agrupado_nombre_region8["CONTEO"] > 2]
print(f"Se eliminaron {size_df_agrupado - df_agrupado_nombre_region8.shape[0]} registros con conteo menor o igual a 2.")

dfs_agrupados = [df_agrupado_nombre, df_agrupado_nombre_region5, df_agrupado_nombre_region8]

Se eliminaron 1744089 registros con conteo menor o igual a 2.
Se eliminaron 1348763 registros con conteo menor o igual a 2.
Se eliminaron 1477695 registros con conteo menor o igual a 2.

In [13]:
df_agrupado_nombre.head(20)

    EDAD_AGRUPADA  CVE_ENTIDAD      SEXO         NOMBRE  CONTEO
0      De 15 a 19            2  FEMENINO        ABIGAIL       3
13     De 15 a 19            2  FEMENINO        ADILENE       3
18     De 15 a 19            2  FEMENINO        ADRIANA       5
32     De 15 a 19            2  FEMENINO      ALEJANDRA       5
36     De 15 a 19            2  FEMENINO          ALEXA       4
41     De 15 a 19            2  FEMENINO      ALEXANDRA       5
55     De 15 a 19            2  FEMENINO         ALICIA       6
64     De 15 a 19            2  FEMENINO     ALMA DELIA       3
70     De 15 a 19            2  FEMENINO        ALONDRA       4
122    De 15 a 19            2  FEMENINO          ANAHI       3
132    De 15 a 19            2  FEMENINO         ANDREA       8
138    De 15 a 19            2  FEMENINO  ANDREA LIZETH       3
143    De 15 a 19            2  FEMENINO         ANGELA       5
150    De 15 a 19            2  FEMENINO       ANGELICA       3
155    De 15 a 19            2  FEMENINO        ARACELI       5
161    De 15 a 19            2  FEMENINO          ARELY       4
203    De 15 a 19            2  FEMENINO        BELINDA       4
220    De 15 a 19            2  FEMENINO         BRENDA       4
253    De 15 a 19            2  FEMENINO         CAMILA       6
266    De 15 a 19            2  FEMENINO       CAROLINA       4

# SELECCIÓN

In [14]:
import numpy as np
from mx_nombres.map_regiones import entidad_a_region



def seleccionar_nombre(edad_agrupada, entidad, sexo, df_agrupados):

    if sexo not in ["FEMENINO", "MASCULINO"]:
        raise ValueError("sexo debe ser 'FEMENINO', 'MASCULINO'")

    filtro = df_agrupados[0][
        (df_agrupados[0]["EDAD_AGRUPADA"] == edad_agrupada) &
        (df_agrupados[0]["SEXO"] == sexo) &
        (df_agrupados[0]["CVE_ENTIDAD"] == entidad)
    ].copy()

    if filtro.empty:
        region8 = entidad_a_region(entidad, modelo=8)
        print("Filtro vacío, buscando por region8:", region8)
        if region8 is not None:
            filtro = df_agrupados[2][
                    (df_agrupados[2]["EDAD_AGRUPADA"] == edad_agrupada) &
                    (df_agrupados[2]["SEXO"] == sexo) & 
                    (df_agrupados[2]["region8"] == region8)
                ].copy()


    if filtro.empty:
        region5 = entidad_a_region(entidad, modelo=5)
        print("Filtro vacío, buscando por region5:", region5)
        if region5 is not None:
            filtro = df_agrupados[1][
                    (df_agrupados[1]["EDAD_AGRUPADA"] == edad_agrupada) &
                    (df_agrupados[1]["SEXO"] == sexo) &
                    (df_agrupados[1]["region5"] == region5)
                ].copy()


    if filtro.empty:
        print("Filtro vacío, no se encontraron nombres para la edad y entidad dadas.")
        return None

    
    return filtro.sample(n=1)["NOMBRE"].iloc[0]  # selección aleatoria

    

edad_agrupada_ = "De 15 a 19"
entidad_ = 1


print(f"Nombre con Femenino: {seleccionar_nombre(
    edad_agrupada=edad_agrupada_, 
    entidad=entidad_, 
    sexo="FEMENINO", 
    df_agrupados=dfs_agrupados)}")
print(f"Nombre masculino: {seleccionar_nombre(
    edad_agrupada=edad_agrupada_, 
    entidad=entidad_, 
    sexo="MASCULINO", 
    df_agrupados=dfs_agrupados)}")

Filtro vacío, buscando por region8: Centronorte
Nombre con Femenino: KATIA
Filtro vacío, buscando por region8: Centronorte
Nombre masculino: ROLANDO

# APELLIDO

In [15]:

df_agrupado_nombre = (
    df_nombres
    .groupby(["EDAD_AGRUPADA", "CVE_ENTIDAD", "SEXO", "SEGUNDO APELLIDO"])
    .size()
    .reset_index(name="CONTEO")
)

size_df_agrupado = df_agrupado_nombre.shape[0]
df_agrupado_nombre = df_agrupado_nombre[df_agrupado_nombre["CONTEO"] > 2]

df_agrupado_nombre.head(20)

   EDAD_AGRUPADA  CVE_ENTIDAD      SEXO SEGUNDO APELLIDO  CONTEO
3     De 15 a 19            2  FEMENINO          ACEVEDO       3
6     De 15 a 19            2  FEMENINO           ACOSTA       7
7     De 15 a 19            2  FEMENINO          AGUILAR      12
15    De 15 a 19            2  FEMENINO         ALVARADO       5
16    De 15 a 19            2  FEMENINO          ALVAREZ      13
24    De 15 a 19            2  FEMENINO          ANTONIO       6
31    De 15 a 19            2  FEMENINO           ARANDA       3
32    De 15 a 19            2  FEMENINO             ARCE       4
38    De 15 a 19            2  FEMENINO          ARMENTA       3
43    De 15 a 19            2  FEMENINO           AVALOS       3
45    De 15 a 19            2  FEMENINO            AVILA       9
47    De 15 a 19            2  FEMENINO            AYALA       7
55    De 15 a 19            2  FEMENINO          BARBOSA       3
63    De 15 a 19            2  FEMENINO         BAUTISTA      17
68    De 15 a 19            2  FEMENINO          BELTRAN       3
72    De 15 a 19            2  FEMENINO        BOJORQUEZ       3
83    De 15 a 19            2  FEMENINO         CALDERON       8
88    De 15 a 19            2  FEMENINO           CAMPOS       5
92    De 15 a 19            2  FEMENINO             CANO       3
96    De 15 a 19            2  FEMENINO          CARMONA       3

# Datos con pocos caractéres

In [23]:
check = df_nombres[df_nombres["SEGUNDO APELLIDO"].str.len() <= 3]
# groupby SEGUNDO APELLIDO 
grouped = check.groupby("SEGUNDO APELLIDO").size().reset_index(name="CONTEO").sort_values(by="CONTEO", ascending=False)
grouped.to_csv(OUTPUTPATH / "segundo_apellidos_cortos.csv", index=False, encoding="latin-1")

In [21]:
check = df_nombres[df_nombres["PRIMER APELLIDO"].str.len() <= 3]
grouped = check.groupby("PRIMER APELLIDO").size().reset_index(name="CONTEO").sort_values(by="CONTEO", ascending=False)
grouped.to_csv(OUTPUTPATH / "primer_apellidos_cortos.csv", index=False, encoding="latin-1")

In [22]:
check = df_nombres[df_nombres["NOMBRE"].str.len() <= 3]
grouped = check.groupby("NOMBRE").size().reset_index(name="CONTEO").sort_values(by="CONTEO", ascending=False)
grouped.to_csv(OUTPUTPATH / "nombres_cortos.csv", index=False, encoding="latin-1")